**<p style="text-align:center; font-size:30px"><u> Exercices de base numpy</u></p>**

# Exercice 1
- créez un numpy array depuis la liste suivante [11.7, 20, 325, 10.2, 11.7, 20]
- remplacez la première occurence de la valeur 11.7 par 5
- remplacez toutes les occurences des valeurs 20 par 0
- calculez la taille (mémoire) du tableau
- modifier le typage en uint8
- calculez la taille du tableau
- Observez les valeurs ? Que s'est-il passé ?

<br>

In [1]:
import numpy as np

In [24]:
arr = np.array([11.7, 20, 325, 10.2, 11.7, 20])
display(arr)

arr[0] = 5
display(arr)

arr[arr == 20] = 0
display(arr)

display(arr.size)

print("ICI")
arr = arr.astype('uint8')
display(arr)

display(arr.size)

array([ 11.7,  20. , 325. ,  10.2,  11.7,  20. ])

array([  5. ,  20. , 325. ,  10.2,  11.7,  20. ])

array([  5. ,   0. , 325. ,  10.2,  11.7,   0. ])

6

ICI


array([ 5,  0, 69, 10, 11,  0], dtype=uint8)

6

# Exercice 2

- créez un numpy array depuis la matrice suivante [[1, 2, 3],  [4, 5, 6], [7, 8, np.nan]]
- affichez:
  - le type de données de la matrice
  - sa forme
  - son nombre de dimension
  - son nombre d'élément
  - Depuis la forme, pouvez-vous obtenir le nombre de dimension et le nombre d'élément ?
- multipliez la dernière colonne par 5 et divisez la première ligne par 0
- modifier le typage en int. Que se passe-t-il ?

<br>

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, np.nan]])
display(arr.dtype)

dtype('float64')

In [31]:
display(arr.shape)

(3, 3)

In [32]:
display(arr.ndim)

2

In [34]:
display(arr.size)

9

In [38]:
n_dims = len(arr.shape)
display(n_dims)

n_elems = arr.shape[1] * arr.shape[0]
display(n_elems)

2

9

In [47]:
new_arr = arr[-1] * 5
display(new_arr)

divide_arr = arr[0] / 0
display(divide_arr)
divide_arr = divide_arr.astype('uint64')
display(divide_arr)

array([35., 40., nan])

/tmp/ipykernel_29346/3144587440.py:4: RuntimeWarning: divide by zero encountered in divide
  divide_arr = arr[0] / 0


array([inf, inf, inf])

/tmp/ipykernel_29346/3144587440.py:6: RuntimeWarning: invalid value encountered in cast
  divide_arr = divide_arr.astype('uint64')


array([0, 0, 0], dtype=uint64)

# Exercice 3

Exercice:
1. Créer la matrice suivante dans la variable x1:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extraire une partie de x1 dans la variable x2
  ```py
      [[50, 60],
       [80, 90]]
````
3. Remplacer le 50 de x2 par 99
4. Réafficher x1

In [55]:
x1 = np.arange(10, 100, 10).reshape(3, 3)
display(x1)

x2 = x1[1:, 1:]
display(x2)

x2[0][0] = 99
display(x2)

display(x1)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

array([[50, 60],
       [80, 90]])

array([[99, 60],
       [80, 90]])

array([[10, 20, 30],
       [40, 99, 60],
       [70, 80, 90]])

# Exercice 4

Exercice:
1. Créer la matrice suivante dans la variable x3:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extraire __une copie__ d'une partie de x3 dans la variable x4
  ```py
      [[50, 60],
       [80, 90]]
````
3. Remplacer le 50 de x4 par 99
4. Réafficher x3

In [61]:
x3 = np.arange(10, 100, 10).reshape(3, 3)
display(x3)

x4 = x3[1:, 1:].copy()
x4[0][0] = 99
x3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# Exercice 5

- créez une matrice (4*4) remplie de valeurs aléatoires comprises entre 2 et 8
- créer un matrice d'identité (*i.e.* une matrice carrée dont la diagonale descendente principale est remplie de 1 et le reste = 0). Proposez plusieurs solutions
- créer une matrice dont la diagonale principale sera remplie de 6 valeurs aléatoires. Proposez plusieurs solutions

(tip: 'zeros','identity', 'fill_diagonal')
<br>

In [66]:
rand_arr = np.random.randint(low=2, high=9, size=(4, 4))
rand_arr

array([[6, 5, 4, 2],
       [7, 5, 4, 2],
       [5, 5, 7, 8],
       [2, 4, 2, 7]])

In [86]:
eye = np.eye(5)
display(eye)

identity = np.identity(5)
display(identity)

diag = np.diag([1., 1., 1., 1., 1.])
display(diag)

rand_diag = np.diag(np.random.rand(4))
display(rand_diag)

new_eye = eye.copy()
new_eye[new_eye == 1] = np.random.randn()
new_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([[0.92220709, 0.        , 0.        , 0.        ],
       [0.        , 0.20711211, 0.        , 0.        ],
       [0.        , 0.        , 0.77647174, 0.        ],
       [0.        , 0.        , 0.        , 0.23263363]])

array([[-0.06660051,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.06660051,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.06660051,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.06660051,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.06660051]])

# Exercice 6

- reproduire la matrice suivante (sans les noms de lignes ou colonnes)
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>10€</td>
      <td>30€</td>
      <td>5€</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>20€</td>
      <td>50€</td>
      <td>1€</td>
    </tr>
    <tr>
      <th>john</th>
      <td>15€</td>
      <td>30€</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>

- affichez le montant total des achats
- affichez les totaux des achats par personne
- affichez les moyennes des achats par type d'aliments

<br>

In [109]:
arr = np.array([[10, 30, 5], [20, 50, 1], [15, 30, np.nan]])
display(arr)

total = np.nansum(arr)
print(total)

total_pps = []
for i in range(3):
    total_pps.append(int(np.nansum(arr[i])))
display(total_pps)

mean_type = {"pates": 0, "legumes": 0, "divers": 0}

mean_type["pates"] = int(np.nanmean(arr[:, 0:1]))
mean_type["legumes"] = int(np.nanmean(arr[:, 1:2]))
mean_type["divers"] = int(np.nanmean(arr[:, -1:]))

mean_type

array([[10., 30.,  5.],
       [20., 50.,  1.],
       [15., 30., nan]])

161.0


[45, 71, 45]

{'pates': 15, 'legumes': 36, 'divers': 3}

# Exercice 7

Cette fois-ci nous avons les quantités achetées ainsi que le prix unitaires pour chacun des éléments

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>1</td>
      <td>4</td>
      <td>2</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>3</td>
      <td>5</td>
      <td>7</td>
    </tr>
    <tr>
      <th>john</th>
      <td>5</td>
      <td>4</td>
      <td>4</td>
    </tr>
  </tbody>
</table>

```py
[20, 5, 3]
````

- calculez le montant total par personne
- calculez le montant total par produit

<br>

In [127]:
quant = np.array([[1, 4, 2], [3, 5, 7], [5, 4, 4]])
prices = np.array([20, 5, 3])

montant_pps = {"bob": 0, "alice": 0, "john": 0}

montant_pps["bob"] = int(np.sum(quant[0] * prices))
montant_pps["alice"] = int(np.sum(quant[1] * prices))
montant_pps["john"] = int(np.sum(quant[2] * prices))

montant_pps

{'bob': 46, 'alice': 106, 'john': 132}

In [144]:
pates = int(np.sum(quant[:, 0:1] * prices[0]))
legumes = int(np.sum(quant[:, 1:2] * prices[1]))
divers = int(np.sum(quant[:, 2:] * prices[2]))

pates, legumes, divers
total = pates + legumes + divers
total

284