In [2]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [178]:
data = pd.DataFrame({
    'A': [1, 2, np.nan, 3, 4, np.nan, 6, 7, 8, 9, np.nan, 11, 12, 2, 2, 3, 4, 3]
})

In [179]:
data

A
0    1.0
1    2.0
2    NaN
3    3.0
4    4.0
5    NaN
6    6.0
7    7.0
8    8.0
9    9.0
10   NaN
11  11.0
12  12.0
13   2.0
14   2.0
15   3.0
16   4.0
17   3.0

In [180]:
imputer = SimpleImputer(strategy='most_frequent')
imputed_data = imputer.fit_transform(data)

print(imputed_data)

[[ 1.]
 [ 2.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 2.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [ 2.]
 [11.]
 [12.]
 [ 2.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 3.]]


In [181]:
data_np = data.to_numpy()
data_np

array([[ 1.],
       [ 2.],
       [nan],
       [ 3.],
       [ 4.],
       [nan],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [nan],
       [11.],
       [12.],
       [ 2.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 3.]])

In [142]:
# Most frequent imputer
count_uniques, count = np.array(np.unique(data_np, return_counts=True))

mask = ~np.isnan(count_uniques)
filtered_unique = count_uniques[mask]
filtered_count = count[mask]

mode_index = np.argmax(filtered_count)
mode = filtered_unique[mode_index]
display(mode)

nan_mask = np.isnan(data_np)

data_np[nan_mask] = mode

data_np

np.float64(3.0)

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 3.],
       [ 4.],
       [ 3.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [ 3.],
       [11.],
       [12.],
       [ 2.],
       [ 2.],
       [ 3.],
       [ 3.],
       [ 3.]])

In [165]:
# Mean imputer
mask = ~np.isnan(data_np)
filtered_data = data_np[mask]
mean = filtered_data.sum() / len(filtered_data)

nan_mask = np.isnan(data_np)
data_np[nan_mask] = mean
data_np

array([[ 1.        ],
       [ 2.        ],
       [ 5.06666667],
       [ 3.        ],
       [ 4.        ],
       [ 5.06666667],
       [ 6.        ],
       [ 7.        ],
       [ 8.        ],
       [ 9.        ],
       [ 5.06666667],
       [11.        ],
       [12.        ],
       [ 2.        ],
       [ 2.        ],
       [ 3.        ],
       [ 3.        ],
       [ 3.        ]])

In [182]:
# Median imputer

mask = ~np.isnan(data_np)
filtered_data = data_np[mask]
median = np.median(filtered_data)

nan_mask = np.isnan(data_np)
data_np[nan_mask] = median
data_np

array([[ 1.],
       [ 2.],
       [ 4.],
       [ 3.],
       [ 4.],
       [ 4.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [ 4.],
       [11.],
       [12.],
       [ 2.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 3.]])